import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Language from "@/components/language";
import { getDictionary } from "@/lib/dictionary"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
  
}: Readonly<{
  children: React.ReactNode;
  params:Promise<{lang:string}>;
}>) {
  const {lang}= await params;
  const dict = await getDictionary(lang as 'es' | 'en')
  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header dict={dict}/> {/* Add the Header component here */}
        <Language/>
        {children}
      </body>
    </html>
  );
}